trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'AKS login, kubeconfig, apply (admin creds)'
  inputs:
    azureSubscription: 'azure-sub-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail
      RG="AksRG"
      AKS="Asha-Aks-Cluster"
      MANIFESTS="k8s"

      az aks install-cli
      az aks get-credentials -g "$RG" -n "$AKS" --admin --overwrite-existing
      kubectl get nodes -o wide

      kubectl apply -f "$MANIFESTS/namespace.yaml"
      kubectl apply -f "$MANIFESTS/deployment.yaml"
      kubectl apply -f "$MANIFESTS/service.yaml"

      kubectl -n nginx-demo rollout status deploy/nginx --timeout=180s
      kubectl -n nginx-demo get svc nginx -o wide
