steps:
- checkout: self

# Login to Azure (uses your service connection)
- task: AzureCLI@2
  displayName: 'Login to Azure'
  inputs:
    azureSubscription: 'azure-sub-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged in with federated identity"

# Install kubectl + kubelogin
- script: |
    az aks install-cli
    echo "PATH after install:"
    echo $PATH
  displayName: 'Install kubectl & kubelogin'

# Get AKS creds and convert kubeconfig for AAD
- script: |
    az aks get-credentials -g $(aksResourceGroup) -n $(aksClusterName) --overwrite-existing
    kubelogin convert-kubeconfig -l azurecli
    kubectl get nodes
  displayName: 'Get AKS credentials & verify cluster access'

# Apply manifests
- script: |
    kubectl apply -f $(manifestsPath)/namespace.yaml
    kubectl apply -f $(manifestsPath)/deployment.yaml
    kubectl apply -f $(manifestsPath)/service.yaml
    kubectl -n nginx-demo rollout status deploy/nginx --timeout=180s
    kubectl -n nginx-demo get svc nginx -o wide
  displayName: 'kubectl apply & rollout status'
