steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'AKS login, kubeconfig, apply'
  inputs:
    azureSubscription: 'azure-sub-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e

      # Tools
      az aks install-cli

      # Kubeconfig
      az aks get-credentials -g $(aksResourceGroup) -n $(aksClusterName) --overwrite-existing
      kubelogin convert-kubeconfig -l azurecli
      kubectl config current-context
      kubectl get nodes

      # Deploy
      kubectl apply -f $(manifestsPath)/namespace.yaml
      kubectl apply -f $(manifestsPath)/deployment.yaml
      kubectl apply -f $(manifestsPath)/service.yaml

      # Verify
      kubectl -n nginx-demo rollout status deploy/nginx --timeout=180s
      kubectl -n nginx-demo get svc nginx -o wide

- script: |
    IP=$(kubectl -n nginx-demo get svc nginx -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
    echo "Public URL: http://$IP/"
  displayName: 'Show public URL'
