trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  aksResourceGroup: 'AksRG'
  aksClusterName: 'Asha-Aks-Cluster'
  manifestsPath: 'k8s'

steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'AKS login, kubeconfig, apply'
  inputs:
    azureSubscription: 'azure-sub-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -euo pipefail
      az aks install-cli
      az aks get-credentials -g "$AKS_RG" -n "$AKS_NAME" --overwrite-existing
      kubelogin convert-kubeconfig -l azurecli
      kubectl config current-context
      kubectl get nodes -o wide
      kubectl apply -f "$MANIFESTS/namespace.yaml"
      kubectl apply -f "$MANIFESTS/deployment.yaml"
      kubectl apply -f "$MANIFESTS/service.yaml"
      kubectl -n nginx-demo rollout status deploy/nginx --timeout=180s
      kubectl -n nginx-demo get svc nginx -o wide
  env:
    AKS_RG: $(aksResourceGroup)
    AKS_NAME: $(aksClusterName)
    MANIFESTS: $(manifestsPath)

- script: |
    set -euo pipefail
    IP=$(kubectl -n nginx-demo get svc nginx -o jsonpath="{.status.loadBalancer.ingress[0].ip}" || true)
    if [ -n "${IP:-}" ]; then
      echo "http://$IP/"
    else
      echo "No external IP yet"
    fi
  displayName: 'Show public URL'
