steps:
- checkout: self

- task: AzureCLI@2
  displayName: 'AKS login, kubeconfig, apply'
  inputs:
    azureSubscription: 'azure-sub-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      az aks install-cli
      az aks get-credentials -g "$AKS_RG" -n "$AKS_NAME" --overwrite-existing
      kubelogin convert-kubeconfig -l azurecli
      kubectl config current-context
      kubectl get nodes

      kubectl apply -f "$MANIFESTS/namespace.yaml"
      kubectl apply -f "$MANIFESTS/deployment.yaml"
      kubectl apply -f "$MANIFESTS/service.yaml"

      kubectl -n nginx-demo rollout status deploy/nginx --timeout=180s
      kubectl -n nginx-demo get svc nginx -o wide
  env:
    AKS_RG: $(aksResourceGroup)
    AKS_NAME: $(aksClusterName)
    MANIFESTS: $(manifestsPath)

- script: |
    set -e
    IP=$(kubectl -n nginx-demo get svc nginx -o jsonpath="{.status.loadBalancer.ingress[0].ip}")
    echo "Public URL: http://$IP/"
  displayName: 'Show public URL'
